#This file was originally generated by PyScripter's unitest wizard

import unittest
from ddt import data, unpack, ddt
import sys

sys.path.append("..\\")
from fuzzycalc.set import *
from fuzzycalc.subset import Gaussian, Triangle

@ddt
class TestFuzzySet(unittest.TestCase):

    def setUp(self):
        self.A = FuzzySet(0, 100, name = 'Classifier')
        self.A.add_term(Gaussian(20, 10),     name = 'term1')
        self.A.add_term(Triangle(30, 50, 75), name = 'term2')

    def testadd_term(self):
        self.assertAlmostEqual(20, self.A['term1'].median)
        self.assertAlmostEqual(50, self.A['term2'].begin_tol)

    @data(
            (0,    22, 'term2'),
            (1,    50, 'term2'),
            (1,    20, 'term1'),
            (0.607,10, 'term1'),
         )
    @unpack
    def testfind(self, res, value, term):
        self.assertAlmostEqual(res, self.A.find(value, term), places=3)

    @data(
            ('term1', 15),
            ('term2', 55),
            ('term2', 40),
         )
    @unpack
    def testclassify(self, res, val):
        self.assertEquals(res, self.A.classify(val))

class TestTriangleClassifier(unittest.TestCase):

    def setUp(self):
        raise NotImplementedError

    def tearDown(self):
        raise NotImplementedError

class TestGaussianClassifier(unittest.TestCase):

    def setUp(self):
        raise NotImplementedError

    def tearDown(self):
        raise NotImplementedError

@ddt
class TestClassifier(unittest.TestCase):

    def setUp(self):
        self.A = Classifier(begin = 10, end = 20,
                             peaks = [10, 13, 18, 20],
                             overlap = 0.2, name = 'sample classifier')

    @data(
            (13.0, 1),
            (13.43, 0.2)
         )
    @unpack
    def testpeaks(self, res, over):
        self.A = Classifier(begin=10, end=20,
                             peaks=[10, 13, 18, 20],
                             overlap=over, name='sample classifier')
        self.assertAlmostEqual(res, self.A['1'].mom(), places=3)

    def testclassify(self):
        self.assertEqual('1', self.A.classify(14))
        self.assertEqual('2', self.A.classify(17))

class TestGlobalFunctions(unittest.TestCase):

    def setUp(self):
        raise NotImplementedError

    def tearDown(self):
        raise NotImplementedError

    def teststd_2_classificator(self):
        raise NotImplementedError

    def teststd_3_classificator(self):
        raise NotImplementedError

    def teststd_5_classificator(self):
        raise NotImplementedError

    def teststd_7_classificator(self):
        raise NotImplementedError

if __name__ == '__main__':
    unittest.main()
