#This file was originally generated by PyScripter's unitest wizard

import unittest
from ddt import data, unpack, ddt
import sys

sys.path.append("..\\")
from fuzzycalc.subset import *

class TestSubset(unittest.TestCase):

    def setUp(self):
        self.subset = Subset()
        self.subset[0.75] = 1

    def test_boundaries(self):
        self.assertAlmostEqual(0, self.subset.domain.begin)
        self.assertAlmostEqual(1, self.subset.domain.end)

    def test_value(self):
        self.assertAlmostEqual(1, self.subset[0.75])

    def test_inner_value(self):
        self.assertAlmostEqual(0.6, self.subset[0.85])

    def test_outer_value(self):
        with self.assertRaises(KeyError):
            self.subset[1.5]

    def testchar(self):
        pass

    def testnormalize(self):
        self.subset = Subset()
        self.subset[0.75] = 0.75
        s2 = self.subset.normalize()

    def testsup(self):
        pass

    def testplot(self):
        pass

    def testlevel(self):
        pass

    def test__getitem__(self):
        pass

    def test__setitem__(self):
        pass

    def testcentr(self):
        pass

    def testcard(self):
        pass

    def testmode(self):
        pass

    def testeuclid_distance(self):
        pass

    def testhamming_distance(self):
        pass

    def test__add__(self):
        pass

    def test__sub__(self):
        pass

    def test__mul__(self):
        pass

    def test__pow__(self):
        pass

    def test__invert__(self):
        pass

    def test__not__(self):
        pass

    def test__neg__(self):
        pass

    def test__and__(self):
        pass

    def test__or__(self):
        pass

    def test__abs__(self):
        pass

    def test__str__(self):
        pass

    def test__cmp__(self):
        pass

    def test__eq__(self):
        pass

    def test__ne__(self):
        pass

class TestTrapezoidal(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testvalue(self):
        pass

    def testcard(self):
        pass

    def testmom(self):
        pass

    def testmode(self):
        pass

    def testmedian(self):
        pass

    def test__eq__(self):
        pass

class TestTriangle(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testvalue(self):
        pass

    def testmode(self):
        pass

    def testcard(self):
        pass

class TestInterval(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testvalue(self):
        pass

    def testcard(self):
        pass

class TestPoint(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testvalue(self):
        pass

    def testplot(self):
        pass

    def testcard(self):
        pass

class TestGaussian(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testvalue(self):
        pass

    def testplot(self):
        pass

    def testcentr(self):
        pass

    def testmode(self):
        pass

    def testcard(self):
        pass

if __name__ == '__main__':
    unittest.main()
